version: '3.0'
services:
  rasa:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command: 
      - run
      - --enable-api
      - --cors
      - "*"
      - --debug
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
